addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.3.0")
addSbtPlugin("io.crashbox"       % "sbt-gpg"      % "0.2.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.12")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.8.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.3.1")